name: Build and Deploy Spring Boot App to EC2 via Docker


on:

  push:

    branches:

      - main


jobs:

  build-and-deploy:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout code

      uses: actions/checkout@v3


    - name: Set up JDK 17

      uses: actions/setup-java@v3

      with:

        java-version: '17'


    - name: Build JAR with Maven

      run: mvn clean package -DskipTests


    - name: Copy files to EC2

      uses: appleboy/scp-action@v0.1.4

      with:

        host: ${{ secrets.EC2_HOST }}

        username: ${{ secrets.EC2_USER }}

        key: ${{ secrets.EC2_SSH_KEY }}

        source: "."

        target: "/home/ubuntu/springboot-docker"


    - name: SSH into EC2 and build & run Docker container

      uses: appleboy/ssh-action@master

      with:

        host: ${{ secrets.EC2_HOST }}

        username: ${{ secrets.EC2_USER }}

        key: ${{ secrets.EC2_SSH_KEY }}

        script: |

          cd springboot-docker

          docker stop springboot-app || true

          docker rm springboot-app || true

          docker build -t springboot-app .

          docker run -d --name springboot-app -p 8080:8080 springboot-app

